version: "3"

services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "4000:4000"
  postgres:
    image: postgres:10
    restart: unless-stopped
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
